//ENTRY(ID,  var,          rightshift,  resolution,     unit,    name,                      minvalue,   maxvalue  )

ENTRY('1', controlPara.targetSpeed, 0,         1.0,       "",    "targetSpeed",               -200.0,     200.0   )
ENTRY('2', controlPara.oversample,  0,         1.0,       "",    "Oversample",                   0.0,      20.0   )
ENTRY('3', controlPara.speedP,      0,         1.0,       "",    "Speed P",                      0.0,    1000.0   )
ENTRY('4', controlPara.speedI,      0,         1.0,       "",    "Speed I",                      0.0,    1000.0   )
ENTRY('5', controlPara.voltageWP,   0,         4.715e-4, "V",    "Voltage WP",                   0.0,       2.0   )
ENTRY('6', controlPara.voltageP,    0,         1.0,       "",    "Voltage P",                    0.0,    1000.0   )
ENTRY('7', controlPara.voltageD,    0,         1.0,       "",    "Voltage D",                    0.0,    1000.0   )
ENTRY(0,   sensorData.voltage,      0,         0.0,      "-",    "Ende der Tabelle",             0.0,       0.0   )
