all:
	g++ -o tool_pc Canvas.cpp Channel.cpp ChannelHandler.cpp main.cpp MeasurementTable.cpp Parameter.cpp Tool.cpp Ui.cpp -L../../freeglut/lib/x64 -I../../freeglut/include -lfreeglut -lopengl32 -lws2_32

